syn match cType "\h\w*_t\w\@!"
syn match cType "\w\@<!boolean\w\@!"
syn match cType "\w\@<!u\{0,1}int\d\{0,3}\w\@!"
syn match cType "\w\@<!TRUE\w\@!"
syn match cType "\w\@<!FALSE\w\@!"

syn match cType "\w\@<!GL\l\+"
syn match cType "\w\@<!GL_TRUE\w\@!"
syn match cType "\w\@<!GL_FALSE\w\@!"
syn match cType "\w\@<!Vector\w\+"
syn match cType "\w\@<!string\w\@!"
